### ISSUE TITLE
Inquiry on Model Performance with ABIDE Dataset

### ISSUE THREAD

**Issue by RRRRendy** [Wayfear/Dynamic-Brain-Transformer#1]
I hope this message finds you well. I am reaching out to inquire about the performance of your model, particularly regarding its testing and results on the ABIDE dataset.
 I have been following your work with great interest. Your model's approach and methodology are impressive, and I am curious to see how it fares with the ABIDE dataset
 Thank you for your dedication to this field and for any information you can provide.

Best regards,

**Comment by Wayfear** [comment]
The ABIDE dataset has high heterogeneity, making it less reliable and showing worse results. Other datasets like PNC, ABCD and HCP are better choices for research.

**Comment by Wayfear** [comment]
After checking, I found we do not conduct experiments on the ABIDE dataset on dynamic brain networks due to its heterogeneous data and shorter time series length compared to other datasets.

**Comment by RRRRendy** [comment]
Thank you for answering my questions, and thank you for your contributions to this field. I look forward to more of your papers and wish you success in your research.
