### ISSUE TITLE
nquiry on Model metric

### ISSUE THREAD

**Issue by Huahuoy** [Wayfear/Dynamic-Brain-Transformer#3]
hello xuan kan,

i want to know how do you select random seed,please tell me more details about your implements ,thank you

**Comment by Wayfear** [comment]
Selecting random seeds violates academic integrity. Our experiment uses 5-fold cross validation. The relevant code logic can be found in Line 40 of [dataloader](https://github.com/Wayfear/Dynamic-Brain-Transformer/blob/main/source/dataset/dataloader.py). Please review it carefully.
